/* 個人資料編輯區：文字使用 {zh: '中文', en: 'English'}。
   照片放 assets/portrait.jpg，CV 放 assets/CV.pdf，再填入下方路徑。
   source 留空時不顯示原始碼連結；請填你的專案網址，而非第三方套件。
*/
window.PROFILE = {
  portrait: '', // './assets/portrait.jpg'
  cv: '', // './assets/CV.pdf'
  linkedin: 'https://www.linkedin.com/in/chin-jung-lin-987876303/',
  github: 'https://github.com/norwellin',
  job104: '',
  introduction: {zh: '這裡預留給我的個人介紹、職涯方向與工作理念。', en: 'A space for my personal introduction, career direction, and approach to work.'}
};
window.COPY = {
  zh: {
    role:'軟體開發 · 自動化測試 · AI 應用',
    intro:'從台灣到德國，累積軟體工程與跨文化協作經驗，將研究與實作轉化為具體的系統與工具。',
    explore:'探索我的專案',download:'下載 CV',cvPending:'CV 檔案待補',photoPending:'個人照片待補',
    aboutTitle:'關於我',aboutLead:'以軟體工程為基礎，探索測試自動化、人工智慧與資料應用。',
    aboutBody:'畢業於大同大學資訊工程學系與德國 HFT Stuttgart Software Technology 碩士學程。專案經驗涵蓋瀏覽器測試錄製、影像與語音處理、資料倉儲，以及國際團隊合作。',
    personalNote:'個人介紹 / 預留文字區',projectsTitle:'研究與實作',projectsIntro:'從研究問題到實際系統，記錄每個專案的方法、成果與我的參與。',
    skillsTitle:'技術與工具',educationTitle:'學習歷程',connect:'與我聯繫',notAdded:'尚未提供',backTop:'回到頂端 ↑',
    details:'專案背景與參與',background:'背景與目標',result:'成果與驗證',contribution:'我的參與',source:'查看原始碼 ↗',
    nav:['首頁','關於','專案','技能','學歷','聯繫'],
    groups:['碩士論文','跨文化合作專案','應用與課程專案','學士畢業專題'],
    teamPending:'參與小組專案；個人負責的模組與工作範圍待補充。'
  },
  en: {
    role:'Software Development · Test Automation · Applied AI',
    intro:'Bringing together software engineering and cross-cultural collaboration, with project experience spanning Taiwan and Germany.',
    explore:'Explore my work',download:'Download CV',cvPending:'CV coming soon',photoPending:'Profile photo coming soon',
    aboutTitle:'A little about me',aboutLead:'A foundation in software engineering. A curiosity for automation, AI, and data.',
    aboutBody:'A graduate of Computer Science and Engineering at Tatung University and the Software Technology master’s program at HFT Stuttgart. My projects span browser test recording, image and speech processing, data warehousing, and international collaboration.',
    personalNote:'Personal introduction / space to complete',projectsTitle:'Research into practice',projectsIntro:'A collection of research and engineering projects, their methods, outcomes, and my contributions.',
    skillsTitle:'Technical toolkit',educationTitle:'Education',connect:'Let’s connect.',notAdded:'Not added yet',backTop:'Back to top ↑',
    details:'Background & contribution',background:'Context & objective',result:'Results & evaluation',contribution:'My contribution',source:'View source code ↗',
    nav:['Home','About','Projects','Skills','Education','Connect'],
    groups:['Master’s thesis','International collaboration','Applied & coursework projects','Bachelor’s capstone'],
    teamPending:'Contributed to this team project; individual responsibilities are to be added.'
  }
};
window.PROJECTS = [
  {id:'thesis',group:0,tag:'MASTER’S THESIS · 2026',image:'thesis.jpg',
   title:{zh:'網頁 GUI 自動化測試錄製系統',en:'Automated GUI Test Recorder'},
   summary:{zh:'以 MobiWebX 為案例，將複雜的瀏覽器操作轉換為可編輯、可回放的 Playwright 測試腳本。',en:'Turning complex browser interactions into editable, replayable Playwright tests, using MobiWebX as a case study.'},
   tools:['JavaScript','Chrome Extension','Playwright','DOM'],
   highlight:{zh:'1,199 個 UI 元件測試，支援率 98.2%；14 個整合情境全數回放成功。',en:'98.2% support across 1,199 UI components; successful replay of all 14 integration scenarios.'},
   background:{zh:'雲端 IDE 的拖放、跨 iframe、多視窗與動態屬性，讓一般測試錄製工具難以產生穩定腳本。',en:'Drag-and-drop, cross-iframe interactions, multiple windows, and dynamic attributes make cloud IDEs challenging for conventional test recorders.'},
   result:{zh:'功能測試中 1,178 / 1,199 個元件成功錄製與回放；14 / 14 個端對端 GUI 建置情境成功。數值為論文指定測試範圍內的結果。',en:'Recorded and replayed 1,178 of 1,199 components and all 14 end-to-end GUI construction scenarios. These results apply to the evaluation scope documented in the thesis.'},
   contribution:{zh:'設計並實作 Chrome 擴充功能、拖拉事件重構、動態定位器排序，以及可視化腳本編輯介面，並執行功能與整合驗證。',en:'Designed and implemented the Chrome extension, drag-event reconstruction, dynamic locator ranking, and visual script editor, with feature and integration validation.'},source:'https://github.com/norwellin/TestingRecorder'},
  {id:'dibuco',group:1,tag:'HFT STUTTGART · TEAM PROJECT',image:'dibuco.jpg',
   title:{zh:'Dibuco 社群資料平台與 ETL 測試',en:'Dibuco Social Data & ETL Testing'},
   summary:{zh:'跨國團隊合作建置社群資料整合平台，針對 Discord 與 Telegram 資料管線驗證擷取、轉換與儲存流程。',en:'An international team project integrating social data, with testing of extraction, transformation, and storage pipelines for Discord and Telegram.'},
   tools:['Python','pytest','ETL','JSON','Docker'],
   highlight:{zh:'報告記錄 Discord 48 案、Telegram 39 案，單元測試全數通過。',en:'Reports document 48 Discord and 39 Telegram unit tests, all passing.'},
   background:{zh:'整合分散在多個社群平台的資訊，為 BigData4Biz 的跨平台資料分析提供資料來源。',en:'Integrate information from multiple social platforms to support cross-platform analysis in BigData4Biz.'},
   result:{zh:'測試涵蓋事件處理、Unicode / emoji、JSON 序列化與檔案儲存。87 案的通過率是報告中的單元測試結果，不代表整個平台的端對端覆蓋率。',en:'Tests cover events, Unicode and emoji, JSON serialization, and file persistence. The 87 passing cases are reported unit tests, not a claim of full-platform end-to-end coverage.'},
   contribution:{zh:'參與專案測試團隊；Discord 與 Telegram 測試報告列於作品資料中。個人測試案例設計、實作與其他模組的分工待補充。',en:'Participated in the testing team. The portfolio includes Discord and Telegram test reports; individual case design, implementation, and other module responsibilities are to be added.'},source:''},
  {id:'weather',group:1,tag:'HFT STUTTGART · DATA ENGINEERING',image:'weather.jpg',
   title:{zh:'即時氣象資料倉儲',en:'Live Weather Data Warehouse'},
   summary:{zh:'從 OpenWeather 擷取 191 個國家與地區首都的氣象資料，建立 ETL 管線、資料倉儲與分析圖表。',en:'Collecting weather observations for 191 national and territorial capitals through OpenWeather, with an ETL pipeline, warehouse, and analytical dashboard.'},
   tools:['Python','FastAPI','MySQL','Docker','Matplotlib'],
   highlight:{zh:'整合容器化資料服務與溫度、降雨、氣壓、日照分析。',en:'Containerized data services with temperature, rainfall, pressure, and daylight analysis.'},
   background:{zh:'將資料倉儲理論應用於持續更新的氣象觀測，透過分層儲存建立可供歷史分析的資料。',en:'Apply data warehouse concepts to continuously updated observations, storing data in layers for historical analysis.'},
   result:{zh:'完成資料擷取、staging、基礎資料庫與倉儲流程，搭配 Matplotlib 儀表板呈現查詢結果。',en:'Implemented extraction, staging, base-database and warehouse stages, with a Matplotlib dashboard presenting query results.'},contribution:null,source:''},
  {id:'rental',group:1,tag:'HFT STUTTGART · DATABASE SYSTEMS',image:'wg-1.jpg',
   title:{zh:'WG 合租住宅管理系統',en:'WG Shared Housing Management'},
   summary:{zh:'以關聯式資料庫管理房客、房間、租約、付款與維修資料，搭配 Java 桌面操作介面。',en:'A relational database for tenants, rooms, contracts, payments, and maintenance, with a Java desktop interface.'},
   tools:['Java','Swing','MySQL','SQL','JDBC'],
   highlight:{zh:'從資料模型設計，延伸至查詢與管理介面實作。',en:'From relational modeling to query and management interface implementation.'},
   background:{zh:'集中管理德國 WG 合租住宅的租務與維護資料，減少資料分散與重複作業。',en:'Centralize rental and maintenance records for shared housing in Germany to reduce fragmented data and repetitive administration.'},
   result:{zh:'報告包含資料模型、SQL 與 Java 程式，提供房客、付款、房間與維修等管理畫面。',en:'The report includes the data model, SQL, Java code, and interfaces for tenant, payment, room, and maintenance management.'},contribution:null,source:'https://github.com/norwellin/HFT_Database_System'},
  {id:'genetic',group:1,tag:'HFT STUTTGART · COMPUTATIONAL INTELLIGENCE',image:'genetic.jpg',
   title:{zh:'基因演算法協商代理',en:'Genetic Algorithm Mediator'},
   summary:{zh:'以基因演算法搜尋生產排程，由中介代理協調供應商與客戶的成本目標。',en:'A genetic algorithm for production scheduling, using a mediator to negotiate supplier and customer cost objectives.'},
   tools:['Java','Genetic Algorithm','Multi-agent Negotiation'],
   highlight:{zh:'比較 27 組選擇、交配與突變策略組合。',en:'Compared 27 combinations of selection, crossover, and mutation strategies.'},
   background:{zh:'雙方代理各自尋求較低生產成本，由中介代理產生候選合約並依投票與適應度更新。',en:'Two agents pursue lower production costs while the mediator generates proposals and updates them using votes and fitness scores.'},
   result:{zh:'以 10、100、1,000 回合比較策略；簡報指出 Temperature Selection、Cycle Crossover 與 Displacement Mutation 在 1,000 回合設定下表現最佳。',en:'Compared strategies over 10, 100, and 1,000 rounds. The presentation identifies temperature selection, cycle crossover, and displacement mutation as the best combination in its 1,000-round experiments.'},contribution:null,source:''},
  {id:'floorplan',group:2,tag:'COMPUTER VISION · OCR',image:'doc-0-2.jpg',
   title:{zh:'平面圖輔助辨識系統',en:'Floor Plan Recognition Assistant'},
   summary:{zh:'運用影像處理與 OCR 辨識超商平面圖中的貨架類別與料號，保留原圖位置供結果標示。',en:'Image processing and OCR for shelf categories and part numbers in store floor plans, preserving coordinates for annotated results.'},
   tools:['Python','OpenCV','Tesseract OCR','TensorFlow / Keras'],
   highlight:{zh:'串接連通元件切割、方向處理、文字辨識與字典校正。',en:'Connected-component segmentation, orientation handling, OCR, and dictionary-based correction.'},
   background:{zh:'平面圖線條密集、文字方向不同，人工辨讀與材料統計耗時，研究以視覺辨識輔助處理。',en:'Dense linework and differently oriented text make manual floor-plan reading and material counting time-consuming.'},
   result:{zh:'歷史簡報記錄類別正確率 80%、類別定位率 100%、料號定位率 27%，約耗時一小時；互動修正與自動材料表仍屬後續工作。',en:'Historical slides report 80% category accuracy, 100% category localization, and 27% part-number localization, taking about one hour. Interactive correction and automated material lists remain future work.'},
   contribution:{zh:'研究 CNN 與 Selective Search 分類路線，以及連通元件、投影切割、Tesseract 與字典校正的文字辨識流程。',en:'Explored CNN classification with Selective Search, and a text-recognition pipeline using connected components, projection segmentation, Tesseract, and dictionary correction.'},source:''},
  {id:'speech',group:2,tag:'BACKEND · SPEECH PROCESSING',image:null,
   title:{zh:'中文語音辨識與合成 API',en:'Chinese Speech Processing API'},
   summary:{zh:'將 Whisper 語音辨識與 gTTS 語音合成封裝為 Flask API，支援錄音轉文字與文字轉 MP3。',en:'A Flask API wrapping Whisper recognition and gTTS synthesis for audio-to-text and text-to-MP3 workflows.'},
   tools:['Python','Flask','Whisper','gTTS','REST API'],
   highlight:{zh:'提供 STT / TTS 端點與 API Key、IP 白名單驗證。',en:'STT / TTS endpoints with API key and IP allowlist checks.'},
   background:{zh:'讓其他應用程式透過 HTTP 使用中文語音處理能力，集中處理模型呼叫與檔案輸入輸出。',en:'Expose Chinese speech processing over HTTP, centralizing model calls and audio file handling.'},
   result:{zh:'完成 API 與檔案處理原型。報告以程式碼檢閱為依據，未驗證正式部署或端對端運行，亦未進行模型訓練。',en:'Implemented the API and file-processing prototype. The report is based on code review; production deployment and end-to-end execution were not verified, and no model training was performed.'},
   contribution:{zh:'整合既有語音模型與套件、API 路由、基本存取限制及獨立音訊上傳測試程式。',en:'Integrated existing models and packages, API routes, basic access restrictions, and a standalone audio-upload test client.'},source:''},
  {id:'asl',group:2,tag:'DEEP LEARNING · OBJECT DETECTION',image:'doc-3-0.jpg',
   title:{zh:'美國手語字母辨識',en:'ASL Alphabet Detection'},
   summary:{zh:'以 YOLOv5 串接 A 至 Z 手勢的資料準備、標註、訓練及圖片與影片推論。',en:'An A–Z hand-gesture detection pipeline using YOLOv5, from data preparation and annotation to image and video inference.'},
   tools:['Python','YOLOv5','PyTorch','Google Colab','Roboflow'],
   highlight:{zh:'26 類字母手勢偵測與混淆矩陣分析。',en:'26 alphabet gesture classes with confusion-matrix analysis.'},
   background:{zh:'以影像辨識將手語字母手勢轉為標籤，探索模型整合與有限運算資源下的訓練配置。',en:'Convert alphabet hand gestures into visual labels and explore training configurations under limited computing resources.'},
   result:{zh:'完成圖片與影片辨識原型，展示字母辨識結果並分析相似手勢誤判。範圍為字母手勢，不包含完整手語句子翻譯。',en:'Produced image and video inference examples and analyzed confusion between similar gestures. The scope is alphabet detection, not full sign-language sentence translation.'},contribution:null,source:''},
  {id:'cnn',group:2,tag:'DEEP LEARNING · EXPERIMENTATION',image:'doc-4-0.jpg',
   title:{zh:'蘋果與貓頭鷹 CNN 模型改進',en:'Iterative CNN Image Classification'},
   summary:{zh:'由二分類基準逐步調整為三分類模型，實驗資料處理、Dropout、影像尺寸與網路深度。',en:'Evolving a binary classifier into a three-class CNN through experiments with preprocessing, dropout, image size, and network depth.'},
   tools:['Python','NNabla','CNN','OpenCV','Selenium'],
   highlight:{zh:'保存的 1,710 張評估影像中，準確率為 97.54%。',en:'97.54% accuracy on 1,710 images in the preserved evaluation records.'},
   background:{zh:'辨識蘋果、貓頭鷹與其他影像，處理二分類模型無法表達「兩者皆非」的情境。',en:'Recognize apples, owls, and other images, addressing cases that do not belong to either original class.'},
   result:{zh:'五層卷積搭配 128 × 128 灰階輸入，1,668 / 1,710 張辨識正確。評估資料包含擴增影像，數值不等同於真實場景的泛化表現。',en:'A five-layer CNN with 128 × 128 grayscale inputs correctly classified 1,668 of 1,710 images. Evaluation includes augmented images and does not establish real-world generalization.'},
   contribution:{zh:'進行資料處理與模型配置實驗，整合單張、批次影像與影片逐影格推論，並分析混淆矩陣。',en:'Experimented with preprocessing and model configurations, integrated single-image, batch, and video-frame inference, and analyzed the confusion matrix.'},source:''},
  {id:'dogs',group:2,tag:'DEEP LEARNING · TRANSFER LEARNING',image:'dogs.jpg',
   title:{zh:'狗品種影像辨識',en:'Dog Breed Image Classification'},
   summary:{zh:'使用 InceptionV3 遷移學習，探索資料切分、最佳化器與 Dropout 對分類訓練的影響。',en:'Exploring InceptionV3 transfer learning with different data splits, optimizers, and dropout settings for dog breed classification.'},
   tools:['Python','InceptionV3','Transfer Learning','Google Colab'],
   highlight:{zh:'比較 Adam、RMSprop、SGD 與不同 Dropout 設定。',en:'Compared Adam, RMSprop, SGD, and different dropout settings.'},
   background:{zh:'以 Stanford Dogs Dataset 為資料來源，透過預訓練模型探索影像分類。',en:'Use the Stanford Dogs Dataset to explore image classification with a pretrained model.'},
   result:{zh:'簡報記錄資料前處理、模型訓練、參數比較與成果展示；未以未核實的數字宣稱最終準確率。',en:'The slides document preprocessing, training, parameter comparisons, and result demonstrations; no unverified final accuracy is claimed.'},
   contribution:{zh:'個人實作範圍與是否為小組專案待補充。',en:'Individual responsibilities and team context are to be added.'},source:''},
  {id:'three',group:2,tag:'WEB GRAPHICS · INTERACTION',image:'doc-1-1.jpg',
   title:{zh:'Three.js 圖學與遊戲機制',en:'Three.js Graphics & Game Mechanics'},
   summary:{zh:'七個瀏覽器互動實作，涵蓋碰撞模擬、角色動畫、鍵盤控制、群體移動與路徑跟隨。',en:'Seven browser-based experiments covering collisions, character animation, keyboard controls, flocking, and path following.'},
   tools:['JavaScript','Three.js','HTML / CSS','WebGL'],
   highlight:{zh:'從 HW0 到 HW6，將幾何與向量運算轉為互動場景。',en:'HW0–HW6 translate geometry and vector calculations into interactive scenes.'},
   background:{zh:'逐步探索即時場景建置、物件運動、動畫狀態與空間判斷，建立瀏覽器圖學基礎。',en:'Explore real-time scenes, object movement, animation states, and spatial reasoning in browser graphics.'},
   result:{zh:'完成七個獨立作品，包括火車動畫、圓盤碰撞、角色控制、避障與 BSP 判斷。作品定位為圖學與遊戲機制實作集合。',en:'Seven independent demos include train animation, disc collisions, character controls, obstacle avoidance, and BSP logic, forming a collection of graphics and game-mechanics experiments.'},
   contribution:{zh:'實作場景、幾何建模、貼圖、動畫更新、輸入控制及代理者移動邏輯。',en:'Implemented scenes, geometry, textures, animation updates, input controls, and agent movement logic.'},source:'https://github.com/norwellin/game-programming'},
  {id:'elevator',group:3,tag:'TATUNG UNIVERSITY · BACHELOR’S CAPSTONE',image:'elevator.jpg',
   title:{zh:'智慧防疫電梯系統',en:'Contactless Smart Elevator System'},
   summary:{zh:'結合非接觸式電梯控制與排班模擬，探索減少接觸操作與兼顧等待時間、能源使用的方法。',en:'Combining contactless elevator controls and scheduling simulations to reduce physical contact and explore waiting-time and energy trade-offs.'},
   tools:['Computer Vision','IoT','Scheduling','Multithreading'],
   highlight:{zh:'整合手勢、人臉辨識與電梯模擬演算法。',en:'Integrated gesture and face recognition with elevator scheduling simulations.'},
   background:{zh:'傳統電梯需要觸碰按鈕，排班效率亦影響乘客等待與能源消耗。團隊開發非接觸控制與軟體排班兩部分。',en:'Traditional elevators require button contact, while scheduling affects passenger waiting and energy use. The team developed contactless controls and scheduling software.'},
   result:{zh:'完成非接觸式控制與排班模擬，依人流情境切換省電及效率模式，並處理多執行緒共享資料的競爭問題。',en:'Implemented contactless controls and scheduling simulations with energy-saving and efficiency modes, and addressed race conditions in shared multithreaded data.'},
   contribution:{zh:'依報告分工表，共同負責資料蒐集、手勢辨識、人臉辨識、電梯介面與電梯模擬演算法。',en:'According to the report’s responsibility table, jointly contributed to research, gesture recognition, face recognition, the elevator interface, and scheduling simulation algorithms.'},source:''}
];
window.SKILLS = [
  {title:{zh:'程式語言',en:'Programming Languages'},items:'Python · Java · JavaScript · C / C++'},
  {title:{zh:'測試與品質工程',en:'Testing & Quality Engineering'},items:'Playwright · Selenium · pytest · GUI Testing'},
  {title:{zh:'機器學習與電腦視覺',en:'Machine Learning & Computer Vision'},items:'TensorFlow / Keras · PyTorch · YOLOv5 · CNN · InceptionV3 · NNabla · OpenCV'},
  {title:{zh:'文字與語音處理',en:'Text & Speech Processing'},items:'Tesseract OCR · Whisper (STT) · gTTS (TTS)'},
  {title:{zh:'資料庫與資料工程',en:'Databases & Data Engineering'},items:'SQL · MySQL · JDBC · phpMyAdmin · ETL · Matplotlib'},
  {title:{zh:'網頁、後端與工具',en:'Web, Backend & Tools'},items:'HTML / CSS · Three.js · Flask · FastAPI · Chrome Extensions · Git · Docker'}
];
window.EDUCATION = [
  {dates:'2024.09 — 2026.08',school:{zh:'Hochschule für Technik Stuttgart',en:'Hochschule für Technik Stuttgart'},degree:{zh:'Software Technology 碩士 · 德國',en:'Master’s degree in Software Technology · Germany'}},
  {dates:'2022.09 — 2026.08',school:{zh:'大同大學',en:'Tatung University'},degree:{zh:'資訊工程學系 碩士 · 台灣',en:'Master’s degree in Computer Science and Engineering · Taiwan'}},
  {dates:'2018.09 — 2022.08',school:{zh:'大同大學',en:'Tatung University'},degree:{zh:'資訊工程學系 學士 · 台灣',en:'Bachelor’s degree in Computer Science and Engineering · Taiwan'}}
];
